---
- hosts: localhost
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  tasks:
    - name: create user
      user:
        name: user1
        state: present
        shell: /bin/bash
        password: '*'
        create_home: yes

